/*
Deployment script for TicketNow

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "TicketNow"
:setvar DefaultFilePrefix "TicketNow"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Eventos].[column_1] (SqlSimpleColumn) will not be renamed to criadorevento';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Eventos].[column_1] (SqlSimpleColumn) will not be renamed to titulo';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Eventos].[column_1] (SqlSimpleColumn) will not be renamed to empresa';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Eventos].[column_1] (SqlSimpleColumn) will not be renamed to eventoTipo';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Eventos].[column_1] (SqlSimpleColumn) will not be renamed to link';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Eventos].[column_1] (SqlSimpleColumn) will not be renamed to classificacaoetaria';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Eventos].[column_1] (SqlSimpleColumn) will not be renamed to estado';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Eventos].[column_1] (SqlSimpleColumn) will not be renamed to cidade';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Eventos].[column_1] (SqlSimpleColumn) will not be renamed to data';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Eventos].[column_1] (SqlSimpleColumn) will not be renamed to termosCondicoes';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[NewTable] (SqlTable) will not be renamed to Eventos';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[NewTable].[column_1] (SqlSimpleColumn) will not be renamed to eventoID';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[FK_Eventos_Eventos] (SqlForeignKeyConstraint) will not be renamed to FK_Eventos_Usuarios';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Eventos].[column_1] (SqlSimpleColumn) will not be renamed to descricao';


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating Table [dbo].[Eventos]...';


GO
CREATE TABLE [dbo].[Eventos] (
    [eventoID]            INT           IDENTITY (1, 1) NOT NULL,
    [criadorevento]       INT           NULL,
    [titulo]              VARCHAR (50)  NULL,
    [empresa]             VARCHAR (50)  NULL,
    [eventoTipo]          INT           NULL,
    [link]                VARCHAR (255) NULL,
    [classificacaoetaria] INT           NULL,
    [estado]              VARCHAR (50)  NULL,
    [cidade]              VARCHAR (50)  NULL,
    [data]                VARCHAR (50)  NULL,
    [termosCondicoes]     VARCHAR (MAX) NULL,
    [descricao]           VARCHAR (MAX) NULL,
    CONSTRAINT [PK_Eventos] PRIMARY KEY CLUSTERED ([eventoID] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating Foreign Key [dbo].[FK_Eventos_Usuarios]...';


GO
ALTER TABLE [dbo].[Eventos] WITH NOCHECK
    ADD CONSTRAINT [FK_Eventos_Usuarios] FOREIGN KEY ([criadorevento]) REFERENCES [dbo].[Usuarios] ([usuarioid]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
GO
